CMP = clang++

all:
	$(CMP) -O3 -Wpedantic -Wall -Wextra -Wconversion --std=c++20 UniquePtr.cpp -o UniquePtr.out

CE:
	$(CMP) -DCE -O3 -Wpedantic -Wall -Wextra -Wconversion --std=c++20 UniquePtr.cpp -o UniquePtr.out