sorter:
	clang++ -O3 -Wall -Wextra -Wpedantic -Wshadow sorter.cpp -o sorter
	chmod +x sorter
generator:
	clang++ -O3 -Wall -Wextra -Wpedantic -Wshadow gen_tests.cpp -o gen_tests
	chmod +x gen_tests
clear:
	rm gen_tests
	rm sorter