CC = g++

all:
	$(CC) -O0 Task2.cpp -o Task2
ub:
	$(CC) -O0 -g Task2_UB.cpp -o Task2_UB
cpp20:
	$(CC) -std=c++20 -O0 Task2.cpp -o Task2
new:
	$(CC) -O0 -g Task2.cpp -o Task2_2
debug:
	$(CC) -O0 -g Task2.cpp -o Task2
asm:
	$(CC) -O0 -S Task2.cpp
clean:
	rm Task2_2
	rm Task_2
	clear