CC = g++

all:
	$(CC) Task1.cpp Task1.hpp -o Task1

proof:
	$(CC) -O0 proof.cpp -o proof
new:
	$(CC) -O0 -g Task1_2.cpp -o Task1_2
debug:
	$(CC) -O0 -g Task1.cpp -o Task1
clean:
	rm Task1_2
	rm proof
	rm Task_1
	clear