CMP = clang++

all:
	$(CMP) -O3 -Wpedantic -Wall -Wextra -Wconversion --std=c++20 Dictionary.cpp -o Dictionary.out

debug:
	$(CMP) -O0 -g -Wpedantic -Wall -Wextra -Wconversion --std=c++20 Dictionary.cpp -o Dictionary.out